# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1--AuBqduJcZQpnzVTN3OZAC4PXyp0JSo
"""

from matplotlib import pyplot as plt
v=[3,4]
u=[1,2,3]
plt.plot([0,v[0]],[0,v[1]])#it's going to print from origin
#plt.plot([-8,-8],[0,0])
#plt.plot([0,0],[8,8])
plt.grid()#shows dimensional grid in 2D x and y
plt.axis((-8,4,-2,6))# x-axis negative,x-axis positive,y-axis -ve,y-axis +ve